name: Release

on:
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'Simple-Pages.zip'
        path: 'kindle'
        directory: 'kindle/dist/'
        exclusions: '*.git* /*node_modules/* .editorconfig /*dist/*'
    - uses: ncipollo/release-action@v1
      with:
        name: "Simple Pages"
        artifacts: "Simple-Pages.zip"
        # bodyFile: "body.md"
        token: ${{ secrets.GITHUB_TOKEN }}
